### ISSUE TITLE
licensing 

### ISSUE THREAD

**Issue by ehsan-g** [SAY-DAO/backend#2]
licensing :monocle_face:

**Comment by iRhonin** [comment]
We have many choices, but I think [GNU GPLv3](https://choosealicense.com/licenses/gpl-3.0/) is more appropriate.

> The GNU GPLv3 also lets people do almost anything they want with your project, except distributing closed source versions.

@ehsan-g tell me what you think.
Check https://choosealicense.com/ for more information.
