### ISSUE TITLE
Refactor Search and Invitation APIs

### ISSUE THREAD

**Issue by iRhonin** [SAY-DAO/backend#28]
As we discussed with @ehsan-g, these changes seem rational: 
- Rename `/family/add` to `/family/join`
- Move logic of accepting invitation to the `/invitations/accept` from `/family/add`
- Change response of `/search/random` from `invitationToken` to `childToken`
- `/family/join` accepts  `childToken` as input data

Any thoughts @ehsan-g?

**Comment by ehsan-g** [comment]
This is how the functions should be called from my end, right?

When  search randomly: `/search/random -->  returns childToken`
When I am choosing a new role : `/family/join /<childToken.familyId>`
When I receive an invitation from another User: `/invitation/accept/<invitationToken> --> /family/join/<childToken.familyId>`

**Comment by iRhonin** [comment]
Yes, correct.

Actually, on the third one, calling `/invitation/accept/<invitationToken>` is enough, and no need to call `/family/join`.


> This is how the functions should be called from my end, right?
> 
> When search randomly: `/search/random --> returns childToken`
> When I am choosing a new role : `/family/join /<childToken.familyId>`
> When I receive an invitation from another User: `/invitation/accept/<invitationToken> --> /family/join/<childToken.familyId>`

**Comment by iRhonin** [comment]
Closed on 1912955cee1f291a6f3e2f02c35c6e49f56f6bf7.

**Comment by iRhonin** [comment]
> Closed on 1912955cee1f291a6f3e2f02c35c6e49f56f6bf7.

Closed wrong issue! Opened agian.

**Comment by iRhonin** [comment]
Closed in 8d439fff1ca89a2a525a68d34e113332d7cce978.
