### ISSUE TITLE
DAO api

### ISSUE THREAD

**Issue by ehsan-g** [SAY-DAO/backend#42]
@iRhonin Please create an public API that will be used in the DAO intro page.
it needs to contain the following:
- all children: Avatar, SAY name, Done needs count, Virtual families' name and avatar

**Comment by ehsan-g** [comment]
Thanks for the Api, please filter the inactive / mock child avatars from data as well. I am getting some extra child data with no image / wrong image @iRhonin

**Comment by iRhonin** [comment]
@ehsan-g Done!
