### ISSUE TITLE
Social Worker Profile Data

### ISSUE THREAD

**Issue by ehsan-g** [SAY-DAO/backend#44]
Name, Code, Avatar , ...

**Comment by iRhonin** [comment]
Please check https://api.sayapp.company/apidocs/#/Social%20Worker%20API/get_api_v2_socialworkers__id_ API.

If there's something you need that are not existed in the current API, please mention it here otherwise we can close this issues.

@ehsan-g

**Comment by ehsan-g** [comment]
@iRhonin Cool,  I was looking at the panel-legacy

**Comment by ehsan-g** [comment]
@iRhonin I couldn't find api for profile details, we have something like this for user but could not find the same for social workers:
`/user/userId=me`
The login also does not return my Id to be able to use it for `/socialworkers/{id}`

**Comment by iRhonin** [comment]
Oh, I will add social worker id to the login response.

But I think adding the whole SW object to the login response is more consistent, the only problem is that is takes more time to implement.

So let me do it in 2 step:

1. [x] Adding SW id to login
2. [ ] Adding SW object to login

**Comment by iRhonin** [comment]
You can now get sw id form login:

```json
{
    "message": "Login Successful",
    "access_token": "ey...",
    "refresh_token": "ey...",
    "id": 123,
}
```
@ehsan-g

**Comment by ehsan-g** [comment]
Perfect
