### ISSUE TITLE
Dynamic CIty and Country 

### ISSUE THREAD

**Issue by ehsan-g** [SAY-DAO/backend#46]
Please create an API to create new city and country, I need them when adding social worker.

**Comment by iRhonin** [comment]
I am searching for a free and open-source database to import it directly into our DB.

**Comment by iRhonin** [comment]
Added Geo APIs in [27d8933](https://github.com/SAY-DAO/backend/commit/27d89331d18d9c04faa5172aafe52bb822f4df60)

Please check https://api.sayapp.company/apidocs/#/Geo%20API to get **Country/State/City**

The next step is adding/migrating the City field to/in SocialWorker.

@ehsan-g

**Comment by iRhonin** [comment]
@ehsan-g Done.

Please reach me for more explanations when you want.

**Comment by ehsan-g** [comment]
@iRhonin Thanks man
