### ISSUE TITLE
API field requirements (Social Workers)

### ISSUE THREAD

**Issue by ehsan-g** [SAY-DAO/backend#47]
Let's have a talk on the fields of some of the apis to rethink weather they should be changed or not. (Not Urgent)

**Comment by ehsan-g** [comment]
Reminder: To talk about ...`/socialworker/children` api

**Comment by iRhonin** [comment]
@ehsan-g
Sorry for the late response, call whenever you are ready.

**Comment by iRhonin** [comment]
@ehsan-g, You can use `sw_id` and `ngo_id` query parameters to filter children by SocialWorker or NGO, please check this API and let me know if there is any problem.

https://api.sayapp.company/apidocs/#/Child%20API/get_api_v2_child_all_confirm__confirm_

**Comment by ehsan-g** [comment]
@iRhonin awesome

**Comment by ehsan-g** [comment]
@Elhamne hey Elham, Arash has added this api for fetching social workers children
