### ISSUE TITLE
Ngo add

### ISSUE THREAD

**Issue by ehsan-g** [SAY-DAO/backend#49]
@iRhonin  am getting this error, which I think is related to the image file:
"The browser (or proxy) sent a request that this server could not understand." (400)

API:    `post(`/ngo/add`, formData, config);`

My Payload:
```
country: 1
phoneNumber: 2274
website: www.example.ca
postalAddress: 15 NorthTown way
logoUrl: (binary)
```

**Comment by iRhonin** [comment]
The error msg is misleading, the real reason is missing fields, these fields are required: 

- logoUrl
- country
- city
- name
- postalAddress
- emailAddress
- phoneNumber

Also, I need to migrate the old city and country fields to the new ones as mentioned in #46. I will do it until tomorrow.

**Comment by iRhonin** [comment]
Removed `city` and `country` fields, added `cityId` and `city` model.

**Comment by ehsan-g** [comment]
btw, I am never in rush for these bugs on GitHub so take your time, for the urgent one I will send you a msg.
