### ISSUE TITLE
Token Header Issue

### ISSUE THREAD

**Issue by ehsan-g** [SAY-DAO/backend#51]
I am sending a transaction similar to my other ones, however for this Api my user token does not go to the header. Any suggestions?
By the way if a need isConfirmed by a mistake, how the need state is reversed to not confirmed? :thinking:
Code:
```
 const config = {
      headers: {
        'Content-type': 'application/json',
        'Authorization': userInfo && userInfo.access_token,
      },
    };

```
`const { data } = await publicApi.patch(`/need/confirm/needId=${needId}`,config);`

`https://api.sayapp.company/api/v2/need/confirm/needId=7256?_lang=en`

Error: message: "Unauthorized, Missing Authorization Header"

**Comment by iRhonin** [comment]
Can you send me a CURL of your request in Telegram? 

You can get that by right clicking on the request and use `copy as CURL`.

About the second question, We don't have `unconfirm` API for needs.
