### ISSUE TITLE
Receipt Status Code = 500

### ISSUE THREAD

**Issue by ehsan-g** [SAY-DAO/backend#54]
When I attempt to add a receipt server responds the following:
 Error: Internal Server Error (500)

`https://api.sayapp.company/api/v2/needs/5680/receipts`

**Comment by iRhonin** [comment]
I guess the problem is in here:

https://github.com/SAY-DAO/ngo-panel-v2/blob/6d84aa11ad74e131c265ed90aa3d5746b3931723/src/redux/actions/reportAction.js#L47

@ehsan-g Please try with `multipart/form-data`.

**Comment by ehsan-g** [comment]
@iRhonin hmmmm. it is working now, I did not change anything! Thanks anyway

**Comment by iRhonin** [comment]
I fixed another bug in the receipts unrelated to this bug but it seems the error msg was misleading!
