### ISSUE TITLE
social worker add

### ISSUE THREAD

**Issue by ehsan-g** [SAY-DAO/backend#58]
@iRhonin  Please remove phone verification on `PhoneNumber` and `EmergancyPhoneNumber` for social workers

**Comment by iRhonin** [comment]
Hi, can you please explain reasoning for that?

**Comment by ehsan-g** [comment]
We are validating only Iranian phone numbers and if we want to store a phone we better use sms services.

**Comment by iRhonin** [comment]
As we talked outside of here, we decided to keep the current validator.
