### ISSUE TITLE
Add child - 500 error

### ISSUE THREAD

**Issue by ehsan-g** [SAY-DAO/backend#62]
@iRhonin 
Request:
`ngo_id: 3,
sw_id: 12239,
awakeAvatarUrl: (binary),
sleptAvatarUrl: (binary),
voiceUrl: blob:http://127.0.0.1:3000/5965c380-f32e-466a-a5e0-8edce2327d8d,
firstName_translations: {"en":"yjte","fa":"tyd"},
lastName_translations: {"en":"yjtj","fa":"gfd"},
sayname_translations: {"en":"54","fa":"ytr"},
bio_translations: {"en":"ytd","fa":"ytf"},
bio_summary_translations: {"en":"';llk","fa":"kl;jhkj"},
phoneNumber: 0912548654,
birthPlace: 35,
country: 98,
city: 1,
birthDate: Wed Oct 12 2022 22:10:09 GMT-0400 (Eastern Daylight Time),
gender: true,
address: 4144,
familyCount: 53,
housingStatus: 1`

Response:
`Access to XMLHttpRequest at 'https://api.sayapp.company/api/v2/child/add/?_lang=en' from origin 'http://127.0.0.1:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

I receive this error when adding child

**Comment by iRhonin** [comment]
Fixed on server.
