### ISSUE TITLE
State field

### ISSUE THREAD

**Issue by ehsan-g** [SAY-DAO/backend#63]
Please add the State field to our db on top of Country and City @iRhonin

**Comment by iRhonin** [comment]
I have added for testing but I think this adds redundancy to the API, can you explain the situation so maybe we find a better solution? @ehsan-g

**Comment by iRhonin** [comment]
Please apply these changes to your projects: 

**Child** APIs:

- `cityId` is **added** which is id of a city
- `birthPlaceId` is **added** which is id of a city
- `nationalityId` is **added** which is id of a country
- `city` is **removed**
- `country` is **removed**
- `birthPlace` is **removed**
- `nationality` is **removed**

**User** APIs:

- `cityId` is **added** which is id of a city
- `city` is **removed**
- `country` is **removed**
- `birthPlace` is **removed**

@ehsan-g @Elhamne

**Comment by iRhonin** [comment]
@ehsan-g, Added these API, maybe it helps you:

- Get Country by id: https://api.s.sayapp.company/apidocs/#/Geo%20API/get_api_v2_countries__id_
- Get State by id: https://api.s.sayapp.company/apidocs/#/Geo%20API/get_api_v2_states__id_
- Get City by id: https://api.s.sayapp.company/apidocs/#/Geo%20API/get_api_v2_cities__id_
